(() => {
  const state = { products: [], cart: JSON.parse(localStorage.getItem('bythehype-cart') || '[]') };
  const $ = (selector) => document.querySelector(selector);
  const formatPrice = (amount, currency = 'INR') => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount);
  const saveCart = () => localStorage.setItem('bythehype-cart', JSON.stringify(state.cart));
  const byId = (id) => state.products.find((product) => product.id === id);
  const cartQuantity = () => state.cart.reduce((total, item) => total + item.quantity, 0);
  function renderCart() { const subtotal = state.cart.reduce((total, item) => total + byId(item.id).price * item.quantity, 0); $('#cartCount').textContent = cartQuantity(); $('#subtotal').textContent = formatPrice(subtotal); $('#cartItems').innerHTML = state.cart.length ? state.cart.map((item) => { const product = byId(item.id); return `<div class="cart-row"><img src="${product.thumbnail}" alt="" /><div><p><strong>${product.name}</strong><br>${formatPrice(product.price)} · Qty ${item.quantity}</p><div class="quantity-controls"><button data-cart-change="-1" data-id="${product.id}" aria-label="Remove one ${product.name}">−</button><button data-cart-change="1" data-id="${product.id}" aria-label="Add one ${product.name}">+</button><button class="remove-button" data-remove="${product.id}">Remove</button></div></div></div>`; }).join('') : '<p class="empty">Your bag is waiting for something good.</p>'; }
  function addToCart(id) { const item = state.cart.find((cartItem) => cartItem.id === id); if (item) item.quantity += 1; else state.cart.push({ id, quantity: 1 }); saveCart(); renderCart(); toggleCart(true); }
  function changeQuantity(id, change) { const item = state.cart.find((cartItem) => cartItem.id === id); if (!item) return; item.quantity += change; if (item.quantity < 1) state.cart = state.cart.filter((cartItem) => cartItem.id !== id); saveCart(); renderCart(); }
  function toggleCart(show) { $('#cart').classList.toggle('open', show); $('#overlay').classList.toggle('visible', show); $('#cart').setAttribute('aria-hidden', String(!show)); }
  function visibleProducts() { const query = $('#productSearch').value.trim().toLowerCase(); const category = $('#categoryFilter').value; const sort = $('#sortProducts').value; const products = state.products.filter((product) => (category === 'all' || product.category === category) && `${product.name} ${product.description} ${product.tags.join(' ')}`.toLowerCase().includes(query)); return products.sort((left, right) => sort === 'price-low' ? left.price - right.price : sort === 'price-high' ? right.price - left.price : sort === 'rating' ? right.rating - left.rating : Number(right.featured) - Number(left.featured) || Number(right.bestseller) - Number(left.bestseller)); }
  function renderProducts() { const products = visibleProducts(); $('#catalogStatus').textContent = `${products.length} product${products.length === 1 ? '' : 's'} found`; $('#products').innerHTML = products.length ? products.map((product) => { const available = product.price > 0; return `<article class="product-card"><a class="product-image" href="pages/product.html?slug=${encodeURIComponent(product.slug)}"><img src="${product.thumbnail}" alt="${product.name}" loading="lazy" />${product.bestseller ? '<span class="tag">Best seller</span>' : product.featured ? '<span class="tag">Featured</span>' : ''}</a><div class="product-info"><div><h3><a href="pages/product.html?slug=${encodeURIComponent(product.slug)}">${product.name}</a></h3><small>${product.category}</small><span class="rating">★ ${product.rating || 'New'} (${product.reviews})</span></div><div class="price"><p>${available ? formatPrice(product.price, product.currency) : 'Price TBD'}</p>${product.originalPrice ? `<del>${formatPrice(product.originalPrice, product.currency)}</del>` : ''}</div></div>${available ? `<button class="quick-add wide" data-add="${product.id}">Add to bag <span>+</span></button>` : `<a class="quick-add wide" href="pages/product.html?slug=${encodeURIComponent(product.slug)}">Pricing placeholder — view details</a>`}</article>`; }).join('') : '<p class="empty">No products match that search yet.</p>'; }
  async function initialise() { try { const [productsResponse, storeResponse] = await Promise.all([fetch('data/products.json'), fetch('data/store.json')]); if (!productsResponse.ok || !storeResponse.ok) throw new Error('Store data could not be loaded.'); const productData = await productsResponse.json(); const store = await storeResponse.json(); state.products = productData.products; state.cart = state.cart.filter((item) => byId(item.id)); saveCart(); document.title = `${store.name} — ${store.tagline}`; $('#announcement').innerHTML = `${store.announcement.primaryText} <span>•</span> ${store.announcement.secondaryText}`; $('#brand').firstChild.textContent = store.name; $('#instagramLink').href = store.social.instagram; $('#pinterestLink').href = store.social.pinterest; [...new Set(state.products.map((product) => product.category))].forEach((category) => $('#categoryFilter').insertAdjacentHTML('beforeend', `<option value="${category}">${category}</option>`)); renderProducts(); renderCart(); } catch (error) { $('#catalogStatus').textContent = 'The collection could not load. Please refresh or use a local web server.'; console.error(error); } }
  $('#products').addEventListener('click', (event) => { const button = event.target.closest('[data-add]'); if (button) addToCart(button.dataset.add); }); $('#cartItems').addEventListener('click', (event) => { const change = event.target.dataset.cartChange; if (change) changeQuantity(event.target.dataset.id, Number(change)); if (event.target.dataset.remove) { state.cart = state.cart.filter((item) => item.id !== event.target.dataset.remove); saveCart(); renderCart(); } }); $('#productSearch').addEventListener('input', renderProducts); $('#categoryFilter').addEventListener('change', renderProducts); $('#sortProducts').addEventListener('change', renderProducts); $('#cartButton').onclick = () => toggleCart(true); $('#closeCart').onclick = () => toggleCart(false); $('#overlay').onclick = () => toggleCart(false); $('#menuButton').onclick = () => { const nav = $('#mainNav'); const open = nav.classList.toggle('open'); $('#menuButton').setAttribute('aria-expanded', String(open)); }; $('#newsletterForm').addEventListener('submit', (event) => { event.preventDefault(); $('#formMessage').textContent = 'Thanks — newsletter delivery will be connected before launch.'; event.target.reset(); }); $('#checkout').onclick = () => window.alert('Checkout is not connected yet. No order has been placed.'); $('#year').textContent = new Date().getFullYear(); initialise();
})();
